version: "3.7"

services:

  pyx:
    image: emcniece/dockeryourxyzzy:latest
    build: ./
    ports:
     - "8080:8080"
    volumes:
      - .pyx:/app
    networks:
      - pyx-net
    env_file: .env

  postgres:
    image: "postgres:alpine"
    volumes:
      - .pgdata:/var/lib/postgresql/data
      - ./init-db.d:/docker-entrypoint-initdb.d
    networks:
      - pyx-net
    env_file: .env

networks:
  pyx-net:
