version: "3.7"

services:

  pyx:
    image: emcniece/dockeryourxyzzy:latest
    build: ./
    ports:
     - "8080:8080"
    volumes:
      - .pyx:/app
    networks:
      - pyx-net
    env_file: .env

  postgres:
    image: "postgres:alpine"
    volumes:
      - .pgdata:/var/lib/postgresql/data
    networks:
      - pyx-net
    env_file: .env

  ngrok:
    image: wernight/ngrok:latest
    networks:
      - pyx-net
    ports:
      - "4040:4040"
    env_file: .env

networks:
  pyx-net:
